//
//  DummyPlaces.swift
//  Keajaiban Dunia
//
//  Created by aanr on 25/04/20.
//  Copyright © 2020 aanr. All rights reserved.
//

import Foundation

var places: [Place] = [
    Place(title: "Rapa Nui", location: "Chile", imageName: "rapa_nui", description: "Dikenal juga dengan nama Easter Island atau Hanga Roa merupakan pulau paling terpencil di dunia. Di sini kamu akan mendapati batu ukiran berukuran besar dari abad ke-13 dan 16. Ada lebih dari 800 monumen batu raksasa yang tersebar di daerah pegunungan vulkanis yang menjadi warisan masyarakat Polinesia yang tinggal di sini sekitar tahun 300 setelah Masehi."),
    Place(title: "Valletta", location: "Malta", imageName: "valletta", description: "Valetta merupakan ibu kota Malta, yang dibangun dari abad ke-16, di bawah kepemimpinan Order of St. John. Kota ini pada dasarnya memiliki gaya bangunan Baroque, dengan elemen arsitektur Mannerist, Neo Classical dan Modern di beberapa area. Dengan tak kurang dari 320 monumen, menjadikan Valletta salah satu area paling bersejarah di dunia."),
    Place(title: "Angkor", location: "Kamboja", imageName: "angkor", description: "Kuil Angkor Wat memang termasuk yang paling terkenal dari kawasan Angkor yang mbentang di lahan seluas 400 km2, termasuk kawasan hutan. Gak hanya itu, di Angkot Thom juga kamu bisa menikmati keindahan Candi Bayon. Kawasan ini termasuk salah satu situs arkeologi paling penting di Asia Tenggara."),
    Place(title: "Acropolis", location: "Yunani", imageName: "acropolis", description: "Acropolis adalah sebuah benteng kuno yang terletak di atas bebatuan tinggi di atas Athena dan salah satu yang terkenal adalah Parthenon. Meski sempat mendapat serangan besar dari Kekaisaran Byzantium situs ini masih berdiri megah sampai sekarang dan menjadi salah satu destinasi favorit di Eropa."),
    Place(title: "Petra", location: "Yordania", imageName: "petra", description: "Posisinya sangat strategis diantara Laur Mati dan Laut Merah, Petra pun menjadi ibu kota kerajaan Nabatea dari abad ke-6 sebelum Masehi. Kota ini kemudian dikuasai Kekaisaran Romawi, tapi akhirnya ditinggalkan di abad ke-2 Masehi menyusul bencana gempa bumi yang melumpuhkan sistem pengelolaan air."),
    Place(title: "Piramida", location: "Mesir", imageName: "piramida", description: "Piramida paling terkenal di Mesir dapat kamu temukan di Giza, di luar Kairo. Piramida Khufu di Giza adalah piramida terbesar di Mesir dan termasuk salah satu tujuh keajaiban dunia."),
    Place(title: "Colosseum", location: "Italia", imageName: "colosseum", description: "Bangunan ini berupa stadion untuk berbagai keriaan zaman dahulu kala, salah satunya pertarungan antara manusia dan binatang. Kaisar Vespasian membangun mulai pada abad 71 Masehi dan selesai pada masa pemerintahan puteranya, Titus, pada abad 80 Masehi. Hingga saat ini bangunan berkapasitas 50 ribu orang ini merupakan contoh gedung pertunjukan terbaik di dunia, dari segi arsitektur hingga kualitas tata suaranya. Waktu terbaik untuk datang: musim sepi turis di Roma berlangsung selama musim dingin, sehingga kerumunan turis bakal berkurang, apalagi jika datang pagi hari saat dibuka atau sore hari sebelum ditutup. Datang di siang hari ke sini sudah pasti terasa panas terik."),
    Place(title: "Great Wall", location: "China", imageName: "wall", description: "Pembangunan Tembok Besar dimulai sekitar 220 Sebelum Masehi saat Dinasti Ming berkuasa. Fungsi bangunan ini menghalau penyerbu ke utara, keluar dari China. Namun orang-orang Mongol berhasil menembus tembok ini pada abad ke-13---dan mendirikan area pemukiman dan perdagangan di kawasan yang sekarang bernama Beijing, di bawah arahan Kublai Khan. Membentang sepanjang 8.852 kilometer, UNESCO menyatakan kalau bangunan ini merupakan contoh luar biasa dari gabungan arsitektur, teknologi, dan seni China kuno. Waktu terbaik untuk datang: rencanakan perjalanan saat musim semi atau musim gugur ketika cuaca lebih cerah dan lebih sedikit turis yang berkunjung."),
    Place(title: "Taj Mahal", location: "India", imageName: "taj_mahal", description: "Taj Mahal adalah bangunan simbol cinta, yang tak hanya cantik tapi juga memiliki nilai arsitektur yang tinggi. Kaisar Mughal Shah Jahan memerintahkan pembangunan pada 1632 sebagai monumen untuk istrinya, Mumtaz Mahal. Struktur yang sangat indah, dianggap sebagai pencapaian arsitektur Indo-Islam, tertinggi saat selesai dibangun pada tahun 1648. Bangunan berbahan dasar marmer putih ini berada di Agra, sekitar 212 kilometer di selatan ibukota India, New Delhi. Waktu terbaik untuk datang: akhir musim semi dan awal musim panas merupakan masa paling gerah di India. Datanglah pada musim hujan atau November hingga Februari. Siapkan waktu kedatangan pagi hari, karena pemandangan matahari terbit di sini sangatlah indah."),
    Place(title: "Borobudur", location: "Indonesia", imageName: "borobudur", description: "Borobudur adalah sebuah candi Buddha yang terletak di Borobudur, Magelang, Jawa Tengah, Indonesia. Candi ini terletak kurang lebih 100 km di sebelah barat daya Semarang, 86 km di sebelah barat Surakarta, dan 40 km di sebelah barat laut Yogyakarta. Candi berbentuk stupa ini didirikan oleh para penganut agama Buddha Mahayana sekitar tahun 800-an Masehi pada masa pemerintahan wangsa Syailendra. Borobudur adalah candi atau kuil Buddha terbesar di dunia, sekaligus salah satu monumen Buddha terbesar di dunia.")
]
